services:
  - type: web
    name: Mimic-Ranking-Extraction-Ket
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn your_app:app
